[project]
name = "lmr-extract"
version = "1.0.0"
description = "BC LDB Liquor Market Review PDF data extraction system"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.0.0",
    "requests>=2.28.0",
    "PyPDF2>=3.0.0",
    "pdfplumber>=0.9.0",
]

[tool.uv.workspace]
members = []